### ISSUE TITLE
Error: Calling Formula.sha1 is disabled

### ISSUE THREAD

**Issue by dan12146** [dan12146/CaffeInstall#1]
Hello! I am trying to install caffe on my Mac OS system and I keep getting the error that tells me to "Please report this to the homebrew/core tap!":

n3-113-178:Homebrew Danny$ brew info boost
# Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/boost.rb:4:in `<class:Boost>'
Please report this to the homebrew/core tap!
n3-113-178:Homebrew Danny$ brew edit panamax.rb
Error: No available formula with the name "panamax.rb" 
n3-113-178:Homebrew Danny$ panamax.rb
-bash: panamax.rb: command not found
n3-113-178:Homebrew Danny$ open panamax.rb
The file /usr/local/Homebrew/panamax.rb does not exist.
n3-113-178:Homebrew Danny$ brew install http://download.panamax.io/installer/brew/panamax.rb
######################################################################## 100.0%
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/Users/Danny/Library/Caches/Homebrew/Formula/panamax.rb:7:in `<class:Panamax>'
n3-113-178:Homebrew Danny$ brew install http://raw.githubusercontent.com/pamri/panamax-coreos/896e6d3820c897f208ee58ba4ba2d5825b420504/panamax.rb
######################################################################## 100.0%
==> Downloading http://download.panamax.io/installer/panamax-0.6.5.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/panamax/0.6.5 --var=/usr/local/var/panamax
==> make install
==> Downloading http://download.panamax.io/panamaxcli/panamaxcli-darwin
######################################################################## 100.0%
==> Caveats
If upgrading the Panamax Installer, be sure to run 'panamax reinstall' to ensure compatibility with other Panamax components.
==> Summary
🍺  /usr/local/Cellar/panamax/0.6.5: 22 files, 6.5MB, built in 36 seconds
n3-113-178:Homebrew Danny$ panamax info

███████╗ ██████╗  █████████╗ ██████╗  ██████████╗ ██████╗  ██╗  ██╗
██╔══██║  ╚═══██╗ ███╗  ███║  ╚═══██╗ ██║ ██╔ ██║  ╚═══██╗ ╚██╗██╔╝
██   ██║ ███████║ ███║  ███║ ███████║ ██║╚██║ ██║ ███████║  ╚███╔╝ 
███████╝ ███████║ ███║  ███║ ███████║ ██║╚██║ ██║ ███████║  ██╔██╗ 
██║      ███████║ ███║  ███║ ███████║ ██║╚██║ ██║ ███████║ ██╔╝ ██╗
╚═╝      ╚══════╝ ╚══╝  ╚══╝ ╚══════╝ ╚═╝ ╚═╝ ╚═╝ ╚══════╝ ╚═╝  ╚═╝

CenturyLink Labs - http://www.centurylinklabs.com/

Checking if required software is installed.

/usr/local/Cellar/panamax/0.6.5/.panamax/desktop: line 56: vagrant: command not found
Please install vagrant version 1.6.3 or newer (https://www.vagrantup.com/downloads.html).
n3-113-178:Homebrew Danny$ brew upgrade http://download.panamax.io/installer/brew/panamax.rb && panamax reinstall
######################################################################## 100.0%
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/Users/Danny/Library/Caches/Homebrew/Formula/panamax.rb:7:in `<class:Panamax>'
n3-113-178:Homebrew Danny$ panamax.rb 
-bash: panamax.rb: command not found
n3-113-178:Homebrew Danny$ open panamax.rb
The file /usr/local/Homebrew/panamax.rb does not exist.
n3-113-178:Homebrew Danny$ HOMEBREW_DEVELOPER=1 brew audit ros/deps/urdfom
Error: No available formula with the name "ros/deps/urdfom" 
Please tap it and then try again: brew tap ros/deps

**Comment by dan12146** [comment]
I understand that Formula.sha1 was disabled in late 2016, however, I cannot figure out how to solve this problem. I have tried many different approaches. Any help would be appreciated
